pic=imread('lena.png')
pic=rgb2gray(pic)

myMax=max((pic(:)))
myMin=min(min(pic,[],'all'))
%disp(myMax)
%disp(myMin)
[row1, col1] = find(ismember(pic, myMax))
[row2, col2] = find(ismember(pic, myMin))
%disp(row1)
disp("Hello")
disp((std(double(pic),0,'all')))
disp((mean(pic,'all')))